### ISSUE TITLE
Summary table of minimal estimated time duration for each question

### ISSUE THREAD

**Issue by HannoaGDavin** [Edouard-Legoupil/XlsFormPrettyPrint#1]
Many thanks for adding to "interview_duration" a module that produces a summary table with a column containing an estimated minimal duration for each question/note.

This table would serve as basis for further visualization (weather tabular or graphs).

**Comment by Edouard-Legoupil** [comment]
@HannoaGDavin  - hello - I have changed the output of the functions so that you have a list with all the elements in it! See https://edouard-legoupil.github.io/XlsFormPrettyPrint/reference/interview_duration.html

**Comment by HannoaGDavin** [comment]
> @HannoaGDavin - hello - I have changed the output of the functions so that you have a list with all the elements in it! See https://edouard-legoupil.github.io/XlsFormPrettyPrint/reference/interview_duration.html

Thanks! I'll give a look and revert to you!
